services:
  - type: web
    name: smart-event-planner-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: OPENWEATHER_API_KEY
        sync: false
    autoDeploy: true
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
